version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nlsearch-backend
    ports:
      - "50051:50051"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - SERVER_ADDRESS=0.0.0.0:50051
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nlsearch-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:50051
    restart: unless-stopped